AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: EC2 Scheduler

Parameters:
  scheduleTag:
    Type: String
    Default: Schedule
    Description: Scheduler definition, hh:mm-hh:mm in UTC format

  scheduleTagDay:
    Type: String
    Default: ScheduleDay
    Description: "Day of the week in ISO format: 1 Monday, 7 Sunday, ..."

  scheduleTagSuspend:
    Type: String
    Default: ScheduleSuspendUntil
    Description: Suspend the scheduler until...


Resources:
  ec2scheduler:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: ec2scheduler
      Handler: main
      Description: EC2 Scheduler - engine
      CodeUri: ./source/scheduler/handler.zip
      MemorySize: 128
      Runtime: go1.x
      Timeout: 60
      Policies:
        - Statement:
          - Effect: "Allow"
            Action:
              - "ec2:DescribeInstanceStatus"
              - "ec2:DescribeInstances"
              - "ec2:DescribeTags"
              - "ec2:StartInstances"
              - "ec2:StopInstances"
            Resource: "*"
      Environment:
        Variables:
          SCHEDULE_TAG: !Ref scheduleTag
          SCHEDULE_TAG_DAY: !Ref scheduleTagDay
      Events:
        Timer:
          Type: Schedule
          Properties:
            Schedule: rate(5 minutes)

  ec2schedulerStatus:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: ec2scheduler-status
      Handler: main
      Description: EC2 Scheduler - status
      CodeUri: ./source/scheduler-status/handler.zip
      MemorySize: 128
      Runtime: go1.x
      Timeout: 30
      Policies:
        - Statement:
          - Effect: "Allow"
            Action:
              - "ec2:DescribeInstanceStatus"
              - "ec2:DescribeInstances"
              - "ec2:DescribeTags"
            Resource: "*"
      Environment:
        Variables:
          SCHEDULE_TAG: !Ref scheduleTag
          SCHEDULE_TAG_DAY: !Ref scheduleTagDay
          SCHEDULE_TAG_SUSPEND: !Ref scheduleTagSuspend
          TEAMS_INTEGRATION: true

  ec2schedulerSet:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: ec2scheduler-set
      Handler: main
      Description: EC2 Scheduler - setter
      CodeUri: ./source/scheduler-set/handler.zip
      MemorySize: 128
      Runtime: go1.x
      Timeout: 30
      Policies:
        - Statement:
          - Effect: "Allow"
            Action:
              - "ec2:CreateTags"
            Resource: "*"
      Environment:
        Variables:
          SCHEDULE_TAG: !Ref scheduleTag
          SCHEDULE_TAG_DAY: !Ref scheduleTagDay

  ec2schedulerDisable:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: ec2scheduler-disable
      Handler: main
      Description: EC2 Scheduler - disable
      CodeUri: ./source/scheduler-disable/handler.zip
      MemorySize: 128
      Runtime: go1.x
      Timeout: 30
      Policies:
        - Statement:
          - Effect: "Allow"
            Action:
              - "ec2:CreateTags"
              - "ec2:DescribeInstances"
              - "ec2:DescribeTags"
            Resource: "*"
      Environment:
        Variables:
          SCHEDULE_TAG: !Ref scheduleTag

  ec2schedulerSuspend:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: ec2scheduler-suspend
      Handler: main
      Description: EC2 Scheduler - suspend
      CodeUri: ./source/scheduler-suspend/handler.zip
      MemorySize: 128
      Runtime: go1.x
      Timeout: 30
      Policies:
        - Statement:
          - Effect: "Allow"
            Action:
              - "ec2:CreateTags"
              - "ec2:DeleteTags"
              - "ec2:DescribeInstances"
            Resource: "*"
      Environment:
        Variables:
          SCHEDULE_TAG: !Ref scheduleTag
          SCHEDULE_TAG_SUSPEND: !Ref scheduleTagSuspend

  ec2schedulerUnsuspend:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: ec2scheduler-unsuspend
      Handler: main
      Description: EC2 Scheduler - unsuspender
      CodeUri: ./source/scheduler-unsuspend/handler.zip
      MemorySize: 128
      Runtime: go1.x
      Timeout: 30
      Policies:
        - Statement:
          - Effect: "Allow"
            Action:
              - "ec2:CreateTags"
              - "ec2:DeleteTags"
              - "ec2:DescribeInstances"
            Resource: "*"
      Environment:
        Variables:
          SCHEDULE_TAG: !Ref scheduleTag
          SCHEDULE_TAG_SUSPEND: !Ref scheduleTagSuspend

  ec2schedulerSuspendMon:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: ec2scheduler-suspend-mon
      Handler: main
      Description: EC2 Scheduler - suspend monitor
      CodeUri: ./source/scheduler-suspend-mon/handler.zip
      MemorySize: 128
      Runtime: go1.x
      Timeout: 30
      Policies:
        - Statement:
          - Effect: "Allow"
            Action:
              - "ec2:CreateTags"
              - "ec2:DeleteTags"
              - "ec2:DescribeInstanceStatus"
              - "ec2:DescribeInstances"
              - "ec2:DescribeTags"
            Resource: "*"
      Environment:
        Variables:
          SCHEDULE_TAG: !Ref scheduleTag
          SCHEDULE_TAG_SUSPEND: !Ref scheduleTagSuspend
      Events:
        Timer:
          Type: Schedule
          Properties:
            Schedule: rate(10 minutes)

