name: test

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - '*'

jobs:
  test:
    strategy:
      matrix:
        go-version: [1.14.x]
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: install Go
      uses: actions/setup-go@master
      with:
        go-version: 1.14.x

    - name: checkout code
      uses: actions/checkout@master

    - name: test scheduler
      run: cd source/scheduler; go test ./... -v -cover

    - name: test scheduler disable
      run: cd source/scheduler-disable; go test ./... -v -cover

